---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5eb9180d50a738001b020112/webhook/forestry
sections:
- type: document
  path: _config.yml
  label: Global site config
  templates:
  - config
- type: document
  path: index.md
  label: Start
  templates:
  - index
- type: directory
  path: products
  label: Product
  create: all
  match: "**/*"
  templates:
  - products
- type: directory
  path: category
  label: Categories
  create: all
  match: "**/*"
  templates:
  - categories
- type: directory
  path: ''
  label: Page
  create: all
  match: "**/*.md"
  exclude: "{README.md,LICENSE.md,index.md,store.md,faq.md,about.md}"
  templates:
  - page
- type: document
  path: store.md
  label: Store
  templates:
  - store
- type: document
  path: faq.md
  label: FAQ
  templates:
  - faq
- type: document
  path: about.md
  label: About
  templates:
  - about
- type: document
  path: _data/promotion.json
  label: Promotion
  templates:
  - promotion
- type: document
  path: _data/testimonials.json
  label: Testimonials
  templates:
  - testimonials
- type: document
  path: _data/menus.yml
  label: Site Menus
  templates:
  - site_menus
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - HUGO_VERSION=0.70.0
  preview_output_directory: _site
  install_dependencies_command: gem install bundler:1.16.6
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
